## 蔡炎龍老師的RNN簡單範例實作

In [1]:
import numpy as np

In [2]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [3]:
def softmax(x):
    e_x = np.exp(x - np.max(x))
    return e_x / e_x.sum()

In [4]:
X1 = np.array([[1], [0], [0]])
X2 = np.array([[0], [1], [0]])
init_state = np.array([[0], [0]])

In [5]:
def RNN(ht_1, input_data):
    #input layer
    Wx = np.array([[1, -1], [1, -1], [1, -1]])
    Wh = np.array([[1, 0.2], [0.2, 1]])
    b = np.array([[0.3], [0.7]])
    
    hidden_state = sigmoid(np.matmul(Wh.transpose(), ht_1) + np.matmul(Wx.transpose(), input_data) + b)
    
    #output layer
    Wout = np.array([[0.3, 1, 0.3], [0.2, -1, 1]])
    bout = np.array([[0.5], [0.5], [0.5]])
    
    output =  softmax(np.matmul(Wout.transpose(), hidden_state) + bout)
    
    return hidden_state, output

In [6]:
t1_hidden_state, t1_output = RNN(init_state, X1)
print('t1_hidden_state \n', t1_hidden_state)
print('t1_output \n', t1_output)

t1_hidden_state 
 [[0.78583498]
 [0.42555748]]
t1_output 
 [[0.29021031]
 [0.30187752]
 [0.40791216]]


In [7]:
t2_hidden_state, t2_output = RNN(t1_hidden_state, X2)
print('t2_hidden_state \n', t2_hidden_state)
print('t2_output \n', t2_output)

t2_hidden_state 
 [[0.89760999]
 [0.57021404]]
t2_output 
 [[0.28379857]
 [0.26836147]
 [0.44783996]]
